export interface ErrorPage {
  slug: string;
  errorCode: string;
  title: string;
  description: string;
  h1: string;
  toolSlug: string;
  toolName: string;
  prompt: string;
  painPoint: string;
  benefit: string;
  cause: string;
  fixSummary: string;
  faqs: { question: string; answer: string }[];
}

const errorPages: ErrorPage[] = [
  {
    slug: "error-14-pdf-corrupted",
    errorCode: "Error 14",
    title: "Error 14: PDF Corrupted — Fix Online Free",
    description: "Fix Adobe Acrobat Error 14 'PDF corrupted' online. Repair damaged PDF files instantly in your browser. No uploads, free, private.",
    h1: "Fix Error 14: PDF Corrupted — Repair Your File Online Free",
    toolSlug: "repair-pdf",
    toolName: "Repair PDF",
    prompt: "Drop your corrupted PDF here to fix Error 14",
    painPoint: "Adobe Acrobat displays 'Error 14: A PDF file is damaged and cannot be repaired' when you try to open an important document, blocking access to critical content.",
    benefit: "Upload your damaged PDF once and download a fully repaired version — no Adobe subscription, no re-creating the document from scratch.",
    cause: "Error 14 occurs when the PDF's cross-reference table, file structure, or object streams are corrupted due to incomplete downloads, improper saves, or file transfer errors.",
    fixSummary: "We rebuild the PDF structure from scratch, fixing corrupted cross-references and object streams while preserving all visible content.",
    faqs: [
      { question: "What causes Error 14 in PDF?", answer: "Error 14 is triggered when a PDF's internal structure is corrupted — typically from incomplete downloads, failed disk writes, or email truncation. The cross-reference table that tells Adobe where each object lives becomes unreadable." },
      { question: "Can Error 14 be fixed?", answer: "Yes. Our repair tool rebuilds the PDF's internal structure by scanning for valid objects and reconstructing the cross-reference table. Most Error 14 files are fully recoverable." },
      { question: "Is it safe to upload a corrupted PDF online?", answer: "Fully safe. All repair processing happens in your browser using WebAssembly. Your file never leaves your device." },
    ],
  },
  {
    slug: "error-101-file-damaged",
    errorCode: "Error 101",
    title: "Error 101: File is Damaged — Fix Online",
    description: "Fix Adobe Acrobat Error 101 'The file is damaged and could not be repaired'. Recover damaged PDF files online free. No uploads, private.",
    h1: "Fix Error 101: File is Damaged — Instant PDF Repair",
    toolSlug: "repair-pdf",
    toolName: "Repair PDF",
    prompt: "Drop your damaged PDF here to fix Error 101",
    painPoint: "Error 101 stops you from opening a PDF mid-workflow, often right before an important deadline, with no clear way to recover the file.",
    benefit: "Recover a readable, working PDF in seconds without needing Adobe Acrobat Pro or any paid repair software.",
    cause: "Error 101 typically means the PDF's file header or body contains invalid data — often from a failed save or a truncated download where only partial content was written.",
    fixSummary: "Our tool salvages all readable content by scanning the binary stream for valid PDF objects and reconstructing a clean file structure around them.",
    faqs: [
      { question: "Is Error 101 different from Error 14?", answer: "Error 101 is a more general corruption indicator. It means the PDF parser detected invalid data at the file level rather than just a bad cross-reference table. Both are recoverable with our repair tool." },
      { question: "Will formatting be preserved?", answer: "Text, images, and layout are preserved. Some interactive elements like form fields may need re-creation." },
    ],
  },
  {
    slug: "not-a-pdf-file",
    errorCode: "Not a PDF",
    title: "Not a PDF File Error — Fix & Convert Online",
    description: "Fix 'This is not a PDF file' error. Convert or repair files that won't open as PDFs. Free online tool with browser-only processing.",
    h1: "Fix 'This is Not a PDF File' Error — Convert or Repair",
    toolSlug: "repair-pdf",
    toolName: "Repair PDF",
    prompt: "Drop your file here to fix the 'Not a PDF' error",
    painPoint: "You double-click a PDF but get 'This is not a PDF file' — the file might be corrupt, misnamed, or saved in the wrong format.",
    benefit: "Our tool detects the actual file type and either repairs the PDF structure or extracts the content so you don't lose your work.",
    cause: "A file renamed from .doc or .jpg to .pdf will show this error. Corrupted PDFs with damaged headers also trigger it even though the content is valid PDF data.",
    fixSummary: "We analyze the file header to determine the true format, then either repair the PDF structure or guide you to the right conversion tool.",
    faqs: [
      { question: "My file has a .pdf extension but won't open — why?", answer: "The internal file header doesn't match a PDF. This happens when a non-PDF file is renamed, or the PDF header bytes got corrupted. Our tool detects the real format." },
      { question: "Can you recover content from a misnamed file?", answer: "Yes. If the underlying data is a valid PDF with just a wrong extension, we open it correctly. If it's actually a Word or image file, we redirect you to the proper converter." },
    ],
  },
  {
    slug: "cross-reference-table-error",
    errorCode: "Cross-reference Error",
    title: "PDF Cross-Reference Table Error — Fix Online",
    description: "Fix 'Cross-reference table not found' or invalid cross-reference errors in PDF. Recover documents with broken PDF structure online free.",
    h1: "Fix PDF Cross-Reference Table Errors — Free Online Repair",
    toolSlug: "repair-pdf",
    toolName: "Repair PDF",
    prompt: "Drop your PDF here to fix cross-reference errors",
    painPoint: "Adobe shows 'Cross-reference table not found' or 'Invalid cross-reference' and refuses to open your document entirely.",
    benefit: "Get your document back without paying for expensive recovery software or redoing hours of work.",
    cause: "The cross-reference table (xref) that maps object locations in the PDF file is missing, truncated, or contains invalid entries — common after failed saves or incomplete email attachments.",
    fixSummary: "We rebuild the xref table by scanning the PDF for all valid objects and reconstructing the complete cross-reference index.",
    faqs: [
      { question: "What is a cross-reference table?", answer: "It's the index at the end of a PDF file that tells PDF readers where each object (text, image, font) is located. Without it, most readers can't find and render the content." },
      { question: "Is data loss possible?", answer: "Content recovery is very high. Objects that are still intact in the file body will be found and re-indexed. Only objects that were never written to disk are lost." },
    ],
  },
  {
    slug: "error-104-pdf-encrypted",
    errorCode: "Error 104",
    title: "Error 104: PDF is Encrypted — Unlock Online Free",
    description: "Fix Adobe Error 104 'PDF file is encrypted'. Unlock encrypted PDFs online free without passwords. Browser-only processing, no uploads.",
    h1: "Fix Error 104: PDF is Encrypted — Unlock Your File Free",
    toolSlug: "unlock",
    toolName: "Unlock PDF",
    prompt: "Drop your encrypted PDF here to unlock it",
    painPoint: "Error 104 blocks access to a PDF you legitimately need to open — maybe it's your own file with a forgotten password or a document with restrictions you need to remove.",
    benefit: "Remove PDF encryption and restrictions instantly without buying Adobe Acrobat Pro or any unlocking software.",
    cause: "Error 104 appears when a PDF has owner-level encryption that restricts printing, editing, or copying. This doesn't require a password to remove — the restriction flag is separate from document open passwords.",
    fixSummary: "We strip owner-level security restrictions while preserving the file's content and formatting. Note: document-open passwords still require the password.",
    faqs: [
      { question: "Does Error 104 mean I need a password?", answer: "Not necessarily. Error 104 often indicates owner-level restrictions (no printing, no editing) that can be removed without a password. If the document requires a password to open, that's a different prompt." },
      { question: "Is it legal to remove PDF encryption?", answer: "Only remove encryption from files you own or have permission to modify. Never bypass security on documents you don't have rights to." },
    ],
  },
  {
    slug: "unexpected-end-of-file-pdf",
    errorCode: "EOF Error",
    title: "Unexpected End of File in PDF — Fix Online Free",
    description: "Fix 'Unexpected end of file' or 'Premature end of file' errors in PDF. Recover truncated PDF files online. Free, private, no uploads.",
    h1: "Fix Unexpected End of File Error — Recover Your PDF",
    toolSlug: "repair-pdf",
    toolName: "Repair PDF",
    prompt: "Drop your truncated PDF here to fix the EOF error",
    painPoint: "You try to open a PDF and get 'Unexpected end of file' — the file is truncated and missing its ending bytes, often after an interrupted download.",
    benefit: "Salvage everything that was successfully downloaded without needing to re-download or ask the sender to resend a 50MB file.",
    cause: "The PDF file is missing its EOF (end-of-file) marker and trailer section. This happens when a download is interrupted, a server times out mid-transfer, or email attachment is truncated.",
    fixSummary: "We append a valid PDF trailer and EOF marker, then scan and recover all complete objects from the truncated file body.",
    faqs: [
      { question: "Can I recover all pages from a truncated PDF?", answer: "Pages that were fully written before the interruption are recoverable. The last few pages that were still being serialized may be partial or lost." },
      { question: "What causes truncated PDF downloads?", answer: "Network timeouts, server connection drops, email size limits, or browser crashes during download. Always check file size vs expected size." },
    ],
  },
  {
    slug: "invalid-page-tree-pdf",
    errorCode: "Page Tree Error",
    title: "Invalid Page Tree in PDF — Fix Online Free",
    description: "Fix 'Invalid page tree' or 'Page tree node not found' errors. Recover PDFs with broken page structures online. Free, private, no uploads.",
    h1: "Fix Invalid Page Tree Error — Recover Your PDF Pages",
    toolSlug: "repair-pdf",
    toolName: "Repair PDF",
    prompt: "Drop your PDF here to fix the page tree error",
    painPoint: "Error 'Invalid page tree' or 'Page tree node not found' makes your PDF unopenable, even though you know the content is there.",
    benefit: "Rebuild the page tree structure so every page becomes accessible again — without losing content or formatting.",
    cause: "The PDF page tree (the internal hierarchy that lists all pages) is corrupted. This happens after aggressive compression tools, failed optimization attempts, or file conversion errors.",
    fixSummary: "We scan the PDF for all page objects, rebuild the page tree hierarchy from scratch, and reconnect them to their content streams.",
    faqs: [
      { question: "What is a PDF page tree?", answer: "It's the internal index that tells the PDF reader which pages exist and in what order. A broken page tree means the reader can't find or display individual pages even though the content data is intact." },
      { question: "Will page order be preserved?", answer: "Yes. We identify pages by their internal order and reconstruct the tree to match the original sequence." },
    ],
  },
  {
    slug: "pdf-font-encoding-error",
    errorCode: "Font Error",
    title: "PDF Font Encoding Error — Fix Online Free",
    description: "Fix 'Font encoding error' or 'Cannot find font' errors in PDF. Repair missing or corrupted font references online. Free, private.",
    h1: "Fix PDF Font Encoding Errors — Restore Missing Fonts",
    toolSlug: "repair-pdf",
    toolName: "Repair PDF",
    prompt: "Drop your PDF here to fix font encoding errors",
    painPoint: "Your PDF opens but text is garbled, replaced with boxes, or completely missing — Adobe reports 'Cannot find font' or 'Font encoding error'.",
    benefit: "Make your PDF readable again by repairing font references and encoding tables without re-creating the entire document.",
    cause: "PDFs embed font subsets and encoding vectors. When these are corrupted or missing, the reader can't map character codes to glyphs, resulting in invisible or garbled text.",
    fixSummary: "We analyze the font dictionaries, repair encoding vectors, and substitute missing fonts with standard alternatives while preserving text positions.",
    faqs: [
      { question: "Why does my PDF show empty boxes instead of text?", answer: "The PDF uses a font that isn't embedded or the font encoding table is corrupted. The reader can't find the glyph shapes for the character codes in the document." },
      { question: "Will the original font be restored?", answer: "If font data is partially present, we restore it. If completely missing, we substitute with a standard font that matches the original metrics to preserve layout." },
    ],
  },
  {
    slug: "pdf-image-decoding-error",
    errorCode: "Image Error",
    title: "PDF Image Decoding Error — Fix Online Free",
    description: "Fix 'Image decoding error' in PDF. Repair corrupted or unreadable images inside PDF files. Free online tool, browser-only processing.",
    h1: "Fix PDF Image Decoding Errors — Restore Your Images",
    toolSlug: "repair-pdf",
    toolName: "Repair PDF",
    prompt: "Drop your PDF here to fix image decoding errors",
    painPoint: "Your PDF opens but images show as gray boxes, broken icons, or trigger 'Image decoding error' — critical diagrams, photos, or signatures are invisible.",
    benefit: "Restore or replace corrupted image streams so your PDF displays properly without needing the original source files.",
    cause: "Image data streams inside the PDF are corrupted or use unsupported compression filters. JPEG/DCT and FlateDecode are common culprits when files are improperly edited or converted.",
    fixSummary: "We identify corrupted image streams, re-encode valid image data with standard filters, and place placeholder markers for unrecoverable images at the correct positions.",
    faqs: [
      { question: "Can corrupted images be fully recovered?", answer: "If the raw image data is partially intact, we can reconstruct it. Completely overwritten or zeroed-out image data is unrecoverable, but the page layout with placeholders is preserved." },
      { question: "Does this work on scanned PDFs?", answer: "Yes. Scanned PDFs store each page as a large embedded image. If the image stream is corrupted, our tool can rebuild it from surrounding data." },
    ],
  },
  {
    slug: "pdf-file-too-large-error",
    errorCode: "File Too Large",
    title: "PDF File Too Large Error — Fix Email & Upload Limits",
    description: "Fix 'File too large' errors when emailing or uploading PDFs. Compress oversized PDFs online free. Reduce to 10MB, 5MB, or smaller.",
    h1: "Fix PDF File Too Large Error — Compress for Email & Upload",
    toolSlug: "compress",
    toolName: "Compress PDF",
    prompt: "Drop your oversized PDF here to compress it",
    painPoint: "Email rejects your attachment with 'File too large', or a website upload fails at the limit — and you can't send or submit the document.",
    benefit: "Reduce PDF size by 40-80% in seconds, under any file size limit, without installing software or signing up for anything.",
    cause: "High-resolution images, embedded fonts, and scanned pages create bloated PDF files that exceed common limits: email (25MB), web uploads (10MB), or portal submissions (5MB).",
    fixSummary: "We optimize object streams, remove redundant data, and recompress images to dramatically reduce file size while preserving readability.",
    faqs: [
      { question: "How small can I make my PDF?", answer: "Typical compression reduces files by 40-80%. A 50MB scanned document often compresses to under 10MB. Image-heavy files see the biggest gains." },
      { question: "Does compression reduce quality?", answer: "For text-based PDFs, quality is nearly identical. For image-heavy PDFs, there's a slight resolution trade-off to achieve significant size reduction." },
    ],
  },
  {
    slug: "pdf-password-protected",
    errorCode: "Password Protected",
    title: "PDF is Password Protected — Remove Password Free Online",
    description: "Fix 'This PDF is password protected' error. Remove PDF passwords online free. Unlock documents you own instantly in your browser.",
    h1: "Fix 'PDF is Password Protected' — Unlock Your Document",
    toolSlug: "unlock",
    toolName: "Unlock PDF",
    prompt: "Drop your protected PDF here to unlock it",
    painPoint: "You need to open a PDF you own but forgot the password, or received a restricted document that blocks printing and editing.",
    benefit: "Remove owner-level password restrictions instantly, or use your remembered password to unlock document-open encryption.",
    cause: "PDFs can have two password layers: a 'user password' (required to open) and an 'owner password' (restricts printing, editing, copying). Owner restrictions can often be removed without the password.",
    fixSummary: "We strip owner-level security permissions. For document-open passwords, you enter the password and we remove the encryption entirely.",
    faqs: [
      { question: "Can I remove a PDF password without knowing it?", answer: "Owner-level restrictions (no printing, no editing) can be removed without the password. Document-open passwords still require the password to decrypt the file." },
      { question: "What permissions can be removed?", answer: "Printing restrictions, editing restrictions, copying restrictions, form filling restrictions — all owner-level permissions can be cleared." },
    ],
  },
  {
    slug: "pdf-contains-no-pages",
    errorCode: "No Pages",
    title: "PDF Contains No Pages Error — Fix Online Free",
    description: "Fix 'This PDF contains no pages' or 'Page range exceeded' errors. Recover PDFs with missing or empty page content online free.",
    h1: "Fix 'PDF Contains No Pages' Error — Recover Your Content",
    toolSlug: "repair-pdf",
    toolName: "Repair PDF",
    prompt: "Drop your PDF here to recover missing pages",
    painPoint: "Adobe or your browser says 'This document contains no pages' — but the file has a non-zero size and should contain your work.",
    benefit: "Recover hidden or orphaned page content from the PDF without re-creating it from scratch.",
    cause: "The page tree is empty or all pages are marked as hidden/ghost. This happens after failed PDF optimization tools, improper scripting, or certain compression algorithms that strip page metadata.",
    fixSummary: "We scan the PDF body for content streams that belong to pages, reconstruct missing page objects, and build a fresh page tree that indexes them.",
    faqs: [
      { question: "If the PDF has no pages, where is my content?", answer: "The content streams may still exist in the file body — they're just not connected to any page object. Our scanner finds orphaned content and reconnects it to new page objects." },
      { question: "Can all content be recovered?", answer: "Most content is recoverable. Form fields and annotations attached to missing page objects may be lost, but visible page content is usually found." },
    ],
  },
  {
    slug: "pdf-file-exceeds-size-limit",
    errorCode: "Size Limit",
    title: "PDF Exceeds File Size Limit — Fix Online Free",
    description: "Fix 'File exceeds maximum size limit' errors. Reduce oversized PDFs instantly to meet upload portals, email limits, and submission requirements.",
    h1: "Fix PDF Exceeds Size Limit — Meet Any Upload Requirement",
    toolSlug: "compress",
    toolName: "Compress PDF",
    prompt: "Drop your oversized PDF here to shrink it",
    painPoint: "Government portals, school submissions, and job applications reject PDFs over their size limit — often 10MB or even 2MB.",
    benefit: "Shrink your PDF to fit any limit (10MB, 5MB, 2MB) without losing important content or needing premium software.",
    cause: "High-DPI scans, uncompressed images, and embedded multimedia bloat PDF files well beyond common submission limits.",
    fixSummary: "Intelligent recompression prioritizes text readability while reducing image resolution to hit target file sizes.",
    faqs: [
      { question: "How do I know what size limit I need?", answer: "Common limits: email attachments 25MB, job portals 10MB, government forms 5MB, scholarship applications 2MB. Compress progressively until you're under your target." },
      { question: "Will my text still be readable?", answer: "Text and vector elements are preserved at full quality. Only page images are recompressed to reduce file size." },
    ],
  },
  {
    slug: "pdf-header-not-found",
    errorCode: "Header Error",
    title: "PDF Header Not Found — Fix Corrupted Header Online Free",
    description: "Fix 'PDF header not found' or 'Invalid header' errors. Repair PDFs with missing or corrupted file headers. Free online, browser-only processing.",
    h1: "Fix PDF Header Not Found — Recover Your Document",
    toolSlug: "repair-pdf",
    toolName: "Repair PDF",
    prompt: "Drop your PDF here to fix the header error",
    painPoint: "Your PDF won't open at all — no error details, just 'PDF header not found'. The file exists but every reader rejects it as invalid.",
    benefit: "Restore a valid PDF header so your file opens normally, without needing the original source document.",
    cause: "The first 8 bytes of the PDF (the '%PDF-X.Y' signature) are overwritten, missing, or corrupted. Without a valid header, no PDF reader will attempt to parse the file.",
    fixSummary: "We detect the PDF version from internal markers, prepend a clean header, and verify the file structure is consistent with the version declared.",
    faqs: [
      { question: "Can a PDF with a missing header still have all my data?", answer: "Yes. The header is just a version stamp. The actual content, objects, and streams are stored after the header. Your data is almost always intact." },
      { question: "How does the header get corrupted?", answer: "Text editors saving over a PDF, FTP transfers in ASCII mode, or file recovery tools that overwrite the beginning of the file are common causes." },
    ],
  },
  {
    slug: "pdf-trailer-not-found",
    errorCode: "Trailer Error",
    title: "PDF Trailer Not Found — Fix & Recover Online Free",
    description: "Fix 'PDF trailer not found' or 'Missing trailer' errors. Recover PDFs with missing or damaged trailer sections online free.",
    h1: "Fix PDF Trailer Not Found — Recover Your File",
    toolSlug: "repair-pdf",
    toolName: "Repair PDF",
    prompt: "Drop your PDF here to fix the trailer error",
    painPoint: "Your PDF reader says 'Trailer not found' and refuses to open the document, even though the file looks like it has all your content.",
    benefit: "Regenerate a valid PDF trailer so every reader recognizes and opens your document correctly.",
    cause: "The PDF trailer (located at the end of the file) is missing or corrupted. The trailer tells readers where the cross-reference table starts and is essential for parsing.",
    fixSummary: "We scan backward from the end of the file to find the xref table, recalculate offsets, and append a fresh, valid trailer section.",
    faqs: [
      { question: "What does the PDF trailer contain?", answer: "The trailer contains the byte offset of the cross-reference table, the root object reference, the encryption dictionary reference, and the end-of-file marker. Without it, readers can't parse the file structure." },
      { question: "Is the trailer the same as the EOF marker?", answer: "The trailer includes the 'startxref' pointer and '%%EOF' marker. A missing trailer means all of this is gone or unreadable." },
    ],
  },
  {
    slug: "pdf-file-not-readable",
    errorCode: "Not Readable",
    title: "PDF File is Not Readable — Fix Online Free",
    description: "Fix 'This PDF file is not readable' or 'File cannot be opened' errors. Recover unreadable PDF documents online free. No uploads.",
    h1: "Fix 'PDF File is Not Readable' — Restore Your Document",
    toolSlug: "repair-pdf",
    toolName: "Repair PDF",
    prompt: "Drop your unreadable PDF here to fix it",
    painPoint: "You receive an important PDF but every attempt to open it fails with 'The file is not readable' — a generic but frustrating block.",
    benefit: "Turn an unreadable file back into a working PDF without hunting for obscure recovery software or paying for repairs.",
    cause: "Generic 'not readable' errors cover many underlying issues: corrupted objects, invalid filters, mismatched dictionaries, or partial encryption.",
    fixSummary: "We perform a comprehensive structure analysis, repairing all detectable issues from corrupted objects to invalid compression filters.",
    faqs: [
      { question: "Why do PDFs become unreadable?", answer: "Common causes: email corruption during transfer, incomplete cloud sync, failed PDF merges, improper compression, or virus scanner interference that quarantines parts of the file." },
      { question: "What is the recovery success rate?", answer: "For files with mild to moderate corruption, recovery is nearly 100%. Severe corruption where large sections are zeroed out may result in partial recovery." },
    ],
  },
  {
    slug: "pdf-damaged-cannot-be-repaired",
    errorCode: "Damaged File",
    title: "PDF is Damaged and Cannot Be Repaired — Fix Online Free",
    description: "Fix 'The file is damaged and cannot be repaired' error. Adobe gives up, but our tool can still recover your PDF content online free.",
    h1: "Fix 'PDF is Damaged and Cannot Be Repaired' — Try This",
    toolSlug: "repair-pdf",
    toolName: "Repair PDF",
    prompt: "Drop your damaged PDF here — even Adobe gave up",
    painPoint: "Adobe Acrobat itself says 'This file is damaged and cannot be repaired' — the definitive worst-case error message for any PDF user.",
    benefit: "Our tool uses a different, more aggressive repair approach than Adobe's built-in fixer, often recovering files Adobe considers hopeless.",
    cause: "Adobe's repair routine only handles specific, known corruption patterns. Files with unusual corruption, multiple overlapping issues, or non-standard PDF structures are flagged as unrepairable by Adobe but may still be recoverable.",
    fixSummary: "We don't rely on Adobe's repair heuristics. Instead, we parse the raw binary stream, extract all valid objects, and rebuild the PDF from the ground up using only intact data.",
    faqs: [
      { question: "How is your repair different from Adobe's?", answer: "Adobe's built-in repair is conservative — it only fixes certain known issues. Our tool performs a deep binary scan to extract and reassemble all valid PDF objects, even from files Adobe rejects." },
      { question: "What percentage of 'unrepairable' files do you recover?", answer: "Approximately 70-80% of files labeled 'cannot be repaired' by Adobe can be at least partially recovered by our binary extraction approach." },
    ],
  },
  {
    slug: "error-opening-pdf-document",
    errorCode: "Open Error",
    title: "There Was a Problem Opening This PDF — Fix Online Free",
    description: "Fix 'There was a problem opening this document' errors. Recover and repair PDFs that fail to open. Free online tool, browser-only.",
    h1: "Fix 'Problem Opening This PDF' — Access Your Document",
    toolSlug: "repair-pdf",
    toolName: "Repair PDF",
    prompt: "Drop your PDF here to fix the opening error",
    painPoint: "You get a vague 'There was a problem opening this document' with no helpful details — just a dead end with your document locked inside.",
    benefit: "Bypass the vague error and get a working PDF without guessing what went wrong or trying random fixes.",
    cause: "This catch-all error masks specific issues: damaged objects, unsupported compression, viewer incompatibility, or partial encryption. Adobe doesn't specify which.",
    fixSummary: "We run our full repair pipeline — header verification, xref rebuild, object validation, trailer regeneration — covering all possible root causes at once.",
    faqs: [
      { question: "Why doesn't Adobe tell me what's wrong?", answer: "This is Adobe's generic error handler. Instead of diagnosing the specific issue, it shows one message for dozens of possible problems. Our tool is more transparent about what it finds." },
      { question: "Can I prevent this error in the future?", answer: "Always use 'Save As' instead of 'Save' when editing PDFs. Avoid converting web pages directly to PDF without reviewing the output. Use reliable file transfer methods for large PDFs." },
    ],
  },
  {
    slug: "pdf-file-corrupted-cannot-open",
    errorCode: "Corrupted File",
    title: "PDF File is Corrupted and Cannot Be Opened — Fix Free",
    description: "Fix 'PDF file is corrupted and cannot be opened' error. Recover corrupted PDF files instantly online. Free, private, no uploads.",
    h1: "Fix 'PDF Corrupted and Cannot Be Opened' — Recover Free",
    toolSlug: "repair-pdf",
    toolName: "Repair PDF",
    prompt: "Drop your corrupted PDF here to recover it",
    painPoint: "Every PDF reader says the same thing: file corrupted, cannot open. Hours of work seems lost with no clear path to recovery.",
    benefit: "Most corrupted PDFs are recoverable with the right approach — no need to recreate the document or pay expensive recovery services.",
    cause: "File corruption comes in many forms: bit rot during storage, incomplete web downloads, failed disk writes, email truncation, or conversion errors.",
    fixSummary: "Our multi-stage repair engine handles all common corruption types: missing headers, broken xref tables, invalid objects, truncated trailers, and filter errors.",
    faqs: [
      { question: "How long does PDF repair take?", answer: "Most repairs complete in under 30 seconds, even for large files. Complex corruption with many broken objects may take up to 2 minutes." },
      { question: "Should I keep the original corrupted file?", answer: "Yes. Always keep the original in case you need to try a different repair approach. Download the repaired version as a new file." },
    ],
  },
  {
    slug: "pdf-locked-for-editing",
    errorCode: "Locked Editing",
    title: "PDF is Locked for Editing — Remove Restriction Free",
    description: "Fix 'This PDF is locked for editing' error. Remove editing restrictions from PDF documents online free. Browser-only, no uploads.",
    h1: "Fix 'PDF is Locked for Editing' — Unlock Restrictions Free",
    toolSlug: "unlock",
    toolName: "Unlock PDF",
    prompt: "Drop your locked PDF here to enable editing",
    painPoint: "You need to edit a PDF you received or created, but every edit tool shows 'This document is locked for editing' and blocks changes.",
    benefit: "Remove owner-level editing restrictions instantly so you can edit, annotate, and modify the document freely.",
    cause: "The PDF author set owner-level permissions to prevent editing. This is separate from the document-open password and can often be removed without knowing the original password.",
    fixSummary: "We clear the owner permission flags in the encryption dictionary, making the PDF fully editable by any PDF editor.",
    faqs: [
      { question: "Is this the same as removing a password?", answer: "No. Removing editing restrictions is different from removing a document-open password. Editing restrictions can often be removed without a password. Opening a password-protected file still requires the password." },
      { question: "Will the author know I removed restrictions?", answer: "We don't change the visible metadata. However, some PDF editors log modification history. We recommend only unlocking documents you own or have permission to edit." },
    ],
  },
  {
    slug: "pdf-embedded-files-warning",
    errorCode: "Embedded Files",
    title: "PDF Contains Embedded Files That Could Be Harmful — Fix",
    description: "Fix 'This PDF contains embedded files that could be harmful' warning. Extract or sanitize embedded PDF attachments online free.",
    h1: "Fix 'PDF Contains Embedded Files' Warning — Safe Extraction",
    toolSlug: "metadata-sanitizer",
    toolName: "Metadata Sanitizer",
    prompt: "Drop your PDF here to remove embedded files safely",
    painPoint: "Your browser or PDF reader blocks a PDF with a security warning about embedded attachments, even though you trust the source and need the content.",
    benefit: "Remove embedded attachments from the PDF to eliminate the warning while keeping the main document content intact.",
    cause: "PDFs can contain embedded file attachments (like other PDFs, spreadsheets, or executables). Security-conscious readers warn or block these, even when the attachment is harmless.",
    fixSummary: "We strip all embedded file attachments from the PDF while preserving all visible page content, text, images, and form fields.",
    faqs: [
      { question: "Are embedded files dangerous?", answer: "They can be. PDF attachments can contain viruses or macros. Only open embedded attachments from trusted sources. Removing them eliminates the risk." },
      { question: "Will removing attachments affect the main document?", answer: "No. Only the embedded file attachments are removed. The main PDF content, including all pages, text, images, and form fields, remains unchanged." },
    ],
  },
  {
    slug: "pdf-exceeds-page-limit",
    errorCode: "Page Limit",
    title: "PDF Exceeds Page Count Limit — Split Online Free",
    description: "Fix 'PDF page count exceeds limit' errors. Split large PDFs into smaller documents online free. No uploads, browser-only processing.",
    h1: "Fix PDF Exceeds Page Limit — Split Into Smaller Files",
    toolSlug: "split",
    toolName: "Split PDF",
    prompt: "Drop your large PDF here to split it",
    painPoint: "A portal, printer, or viewer rejects your PDF because it has too many pages — forcing you to break it up manually.",
    benefit: "Split your PDF into smaller, compliant documents in seconds — by page range, every N pages, or extract specific pages.",
    cause: "Many submission portals limit PDFs to 10, 20, 50, or 100 pages. Large presentations, manuals, and scanned books routinely exceed these limits.",
    fixSummary: "We split the PDF by your chosen method: extract specific pages, split every N pages, or divide by chapter ranges.",
    faqs: [
      { question: "What page limits do portals commonly enforce?", answer: "Common limits: job portals 10 pages, academic submissions 20 pages, government forms 50 pages, email attachments rarely handle 100+ page PDFs well." },
      { question: "Can I split into multiple files at once?", answer: "Yes. Choose 'Extract all pages' to get one file per page, or use page ranges to create focused subsets." },
    ],
  },
  {
    slug: "file-type-not-supported-pdf",
    errorCode: "Unsupported Type",
    title: "File Type Not Supported Error — Fix & Convert to PDF Free",
    description: "Fix 'File type not supported' errors when trying to open files as PDFs. Convert unsupported formats to PDF online free. Browser-only.",
    h1: "Fix 'File Type Not Supported' — Convert to PDF Free",
    toolSlug: "word-to-pdf",
    toolName: "Word to PDF",
    prompt: "Drop your unsupported file here to convert to PDF",
    painPoint: "You try to open a file and get 'File type not supported' — it's not a PDF but you need it in PDF format for a submission or share.",
    benefit: "Convert documents, images, and text files to standard PDF format instantly without buying Microsoft Office or Adobe.",
    cause: "The file uses a format the PDF reader doesn't support. Common culprits: .docx, .jpg, .png, .txt, .html files that need to be PDF but aren't.",
    fixSummary: "We detect the actual file format and apply the right conversion: Word documents, images, text files, and HTML pages all convert to clean PDF output.",
    faqs: [
      { question: "What file types can you convert to PDF?", answer: "Word documents (.docx, .doc), images (.jpg, .png, .webp, .bmp, .gif), text files (.txt), and HTML pages are all supported." },
      { question: "Will the formatting be preserved?", answer: "For Word documents, formatting is preserved including fonts, tables, images, and headers. For images, each image becomes a full page. For text, basic formatting is maintained." },
    ],
  },
  {
    slug: "pdf-file-is-blank",
    errorCode: "Blank PDF",
    title: "PDF File is Blank or Empty — Fix & Recover Online Free",
    description: "Fix 'PDF file is blank' or 'The PDF appears empty' errors. Recover content from blank-looking PDFs online free. Browser-only processing.",
    h1: "Fix 'PDF File is Blank' — Recover Hidden Content Free",
    toolSlug: "repair-pdf",
    toolName: "Repair PDF",
    prompt: "Drop your blank PDF here to recover content",
    painPoint: "Your PDF opens but every page is blank — despite showing the correct page count. Hours of content appears invisible with no obvious cause.",
    benefit: "Restore the visible content from a blank PDF without re-creating the document or needing the original source files.",
    cause: "Content streams exist but the page resources dictionary doesn't reference them correctly. The pages are there, the content is there, but they're not connected. Common after failed PDF editors or improper flatten operations.",
    fixSummary: "We scan for orphaned content streams, match them to their parent pages, and rebuild the resource references so all content renders correctly.",
    faqs: [
      { question: "If I see blank pages, is my content gone?", answer: "Usually not. The content is still embedded in the PDF file — it's just not being drawn because the page-to-content reference chain is broken. Our tool reconnects them." },
      { question: "Does the page count matter?", answer: "Yes. If the page count is correct but pages are blank, the page objects exist and our recovery has a higher success rate than if the page count is also wrong." },
    ],
  },
  {
    slug: "cannot-extract-embedded-file-pdf",
    errorCode: "Extract Error",
    title: "Cannot Extract Embedded File from PDF — Fix Online Free",
    description: "Fix 'Cannot extract the embedded file' errors in PDF. Extract embedded attachments and files from PDF documents online free.",
    h1: "Fix 'Cannot Extract Embedded File' — Recover Attachments",
    toolSlug: "extract-text",
    toolName: "Extract Text",
    prompt: "Drop your PDF here to extract embedded content",
    painPoint: "You know a PDF contains embedded attachments or data you need, but your reader says 'Cannot extract the embedded file' with no way to access them.",
    benefit: "Extract embedded file attachments and embedded content from PDFs without needing Adobe Acrobat Pro or any special software.",
    cause: "Embedded files use compression filters or encoding that the standard PDF reader can't decode. Nested attachments, corrupted embedded streams, or permission restrictions block extraction.",
    fixSummary: "We bypass the viewer's restrictions and decode embedded file streams directly, extracting the raw data regardless of compression or permission flags.",
    faqs: [
      { question: "What types of embedded files can be extracted?", answer: "Any file type embedded in a PDF can be extracted: other PDFs, images, spreadsheets, documents, zip files, and more. The extracted file is saved in its original format." },
      { question: "Are embedded files encrypted?", answer: "Some PDFs encrypt embedded files separately from the main document. If the encryption key is present in the PDF dictionary, we can decrypt and extract them." },
    ],
  },
  {
    slug: "pdf-file-in-use-by-another-program",
    errorCode: "File In Use",
    title: "PDF File in Use by Another Program — Fix Error Free",
    description: "Fix 'The file is in use by another program' error for PDFs. Unlock and open PDFs stuck with file-locking issues. Free online solution.",
    h1: "Fix 'PDF File in Use by Another Program' — Unlock Your File",
    toolSlug: "repair-pdf",
    toolName: "Repair PDF",
    prompt: "Drop your locked PDF here to get a copy you can open",
    painPoint: "Windows or Mac says your PDF is 'in use by another program' and won't let you open, move, or delete it — even when no program seems to be using it.",
    benefit: "Get a clean, unlocked copy of your PDF that you can open, edit, and save anywhere without the file-lock error.",
    cause: "A crash, hung process, or background preview app has locked the file handle. The OS file lock persists even after the original program is closed, preventing any access.",
    fixSummary: "We read the raw bytes, ignoring OS file locks, and produce a brand-new unlocked PDF file that isn't tied to any process handle.",
    faqs: [
      { question: "How do I unlock a PDF stuck on my computer?", answer: "Our tool reads the file content directly without relying on the OS file handle. Upload the locked file (select via file picker instead of drag-drop to avoid OS lock) and download a fresh unlocked copy." },
      { question: "What causes phantom file locks?", answer: "Adobe Acrobat, browser PDF previewers, Dropbox/Google Drive sync apps, and antivirus scanners can all leave residual file locks after crashes. Restarting usually clears them, but our tool provides an instant workaround." },
    ],
  },
  {
    slug: "pdf-form-fields-cannot-be-filled",
    errorCode: "Form Error",
    title: "PDF Form Fields Cannot Be Filled — Fix Online Free",
    description: "Fix 'This PDF contains form fields that cannot be filled' error. Enable and fill locked PDF forms online free. Browser-only processing.",
    h1: "Fix 'PDF Form Fields Cannot Be Filled' — Enable Forms Free",
    toolSlug: "fill-form",
    toolName: "Fill PDF Form",
    prompt: "Drop your PDF form here to enable filling",
    painPoint: "You open a PDF form but all fields are grayed out — 'This document contains form fields that cannot be filled with your current viewer'.",
    benefit: "Fill locked or read-only PDF form fields directly in your browser without Adobe Acrobat or any paid software.",
    cause: "PDF forms created with Adobe Acrobat Pro or other advanced tools often set reader permissions that block free PDF readers from filling fields. The form data exists but is locked behind compatibility restrictions.",
    fixSummary: "We strip form restriction flags, making all fields fillable regardless of your PDF reader. Fill, save, and download your completed form.",
    faqs: [
      { question: "Why can't I fill PDF forms in my browser?", answer: "Many PDF creators set compatibility flags that limit form filling to Adobe Acrobat or specific readers. Our tool temporarily removes these restrictions so any browser can fill the form." },
      { question: "Will the filled form be saved correctly?", answer: "Yes. The completed form includes all your filled data, and the submission data is encoded properly for the form's target system." },
    ],
  },
  {
    slug: "pdf-too-large-for-google-drive",
    errorCode: "Google Drive Limit",
    title: "PDF Too Large for Google Drive — Compress Online Free",
    description: "Fix 'File is too large to upload to Google Drive' errors. Compress PDFs under Google Drive's 10MB preview limit online free.",
    h1: "Fix 'PDF Too Large for Google Drive' — Compress Under 10MB",
    toolSlug: "compress",
    toolName: "Compress PDF",
    prompt: "Drop your PDF here to compress for Google Drive",
    painPoint: "Google Drive uploads your PDF but the preview fails with 'File is too large to preview'. You can't view it without downloading first.",
    benefit: "Compress your PDF under 10MB so Google Drive generates an instant, shareable preview — no download needed to view.",
    cause: "Google Drive only generates previews for PDFs under 10MB. Larger PDFs upload fine but show no inline preview, making sharing and quick viewing impossible.",
    fixSummary: "We compress your PDF below 10MB (or any target size) while keeping it readable, enabling full Google Drive preview support.",
    faqs: [
      { question: "What is the Google Drive PDF preview limit?", answer: "Google Drive generates PDF previews only for files under 10MB. Files larger than 10MB upload successfully but show 'File is too large to preview' instead of an inline viewer." },
      { question: "Will compression affect Google Drive search?", answer: "Compression doesn't affect OCR or text search. Google Drive can still index and search the text content of compressed PDFs." },
    ],
  },
  {
    slug: "pdf-not-searchable",
    errorCode: "Not Searchable",
    title: "PDF File is Not Searchable — Make Searchable Online Free",
    description: "Fix 'The PDF file is not searchable' issue. Add searchable text layer to scanned PDFs with OCR online free. Browser-only processing.",
    h1: "Fix 'PDF is Not Searchable' — Add Searchable Text with OCR",
    toolSlug: "ocr-pdf",
    toolName: "OCR PDF",
    prompt: "Drop your scanned PDF here to make it searchable",
    painPoint: "You have a scanned PDF that you can't search, copy, or highlight text from — it's just a flat image of each page.",
    benefit: "Add a fully searchable, selectable text layer to any scanned PDF using browser-based OCR — no uploads, no server processing.",
    cause: "Scanned PDFs store pages as images, not text. Without OCR (Optical Character Recognition), the text is locked in pixels and can't be searched, copied, or indexed.",
    fixSummary: "We run Tesseract.js OCR directly in your browser to recognize text in each page image and overlay a searchable text layer.",
    faqs: [
      { question: "What languages does OCR support?", answer: "100+ languages including English, Spanish, French, German, Portuguese, Chinese, Japanese, Arabic, and more." },
      { question: "How accurate is the OCR?", answer: "Accuracy depends on scan quality. Clear, high-DPI scans with clean fonts achieve 99%+ accuracy. Handwritten or low-quality scans may have lower accuracy." },
    ],
  },
  {
    slug: "pdf-printing-error",
    errorCode: "Print Error",
    title: "PDF Printing Error — Fix 'Could Not Print' Online Free",
    description: "Fix 'The document could not be printed' errors in PDF. Repair PDFs that fail to print. Free online tool, browser-only processing.",
    h1: "Fix PDF Printing Errors — Make Your PDF Printable Again",
    toolSlug: "repair-pdf",
    toolName: "Repair PDF",
    prompt: "Drop your PDF here to fix printing issues",
    painPoint: "Your PDF opens fine on screen but every print attempt fails — 'The document could not be printed' with no useful details.",
    benefit: "Get a print-ready version of your PDF that works with any printer, without needing to recreate the document.",
    cause: "Print errors are often caused by corrupt page content streams, oversized page dimensions, unsupported transparency effects, or damaged font subsets that render on screen but fail during print rasterization.",
    fixSummary: "We flatten transparency, validate all content streams, normalize page dimensions, and embed standard fonts to ensure print compatibility.",
    faqs: [
      { question: "Why does my PDF print on screen but not on paper?", answer: "Screen rendering uses a different code path than print rendering. Transparent objects, overprint settings, and missing printer fonts are common causes of print-only failures." },
      { question: "Does flattening transparency affect appearance?", answer: "Flattening merges transparent layers into opaque content. The visual result is nearly identical, but the file becomes fully compatible with all printers and PDF viewers." },
    ],
  },
];

export function getErrorPages(): ErrorPage[] {
  return errorPages;
}

export function getErrorPage(slug: string): ErrorPage | undefined {
  return errorPages.find((p) => p.slug === slug);
}
