import { getAuthenticatedSession } from "@/lib/auth/request";
import {
  getPremiumStatus,
  getPremiumStatusByUserId,
  grantConfiguredPremium,
  isAdminPremiumEmail,
} from "@/lib/kv";
import { validateString } from "@/lib/validation";

/**
 * The trial allowance is keyed to the strongest stable identity available:
 * the authenticated account when a valid session cookie exists, otherwise
 * the anonymous client ID generated by the browser. Client-side counters are
 * never trusted — this module only reads the HttpOnly session and KV state.
 */
export interface UsageIdentity {
  identity: string;
  kind: "user" | "client";
  premium: boolean;
  email?: string;
  userId?: string;
}

/** Client IDs are UUIDs generated by the browser; restrict the charset so
 * identity strings can never collide or traverse the key namespace. */
export function sanitizeClientId(raw: unknown): string | null {
  const value = validateString(raw, 100);
  if (!value) return null;
  return /^[A-Za-z0-9_-]{8,100}$/.test(value) ? value : null;
}

export function sanitizeReservationId(raw: unknown): string | null {
  return sanitizeClientId(raw);
}

/**
 * Resolve the allowance identity and Premium state for a request. A valid
 * HttpOnly session always wins over the anonymous client ID, so the lifetime
 * trial follows the account across devices whenever the user is signed in.
 */
export async function resolveUsageIdentity(
  request: Request,
  rawClientId: unknown,
): Promise<UsageIdentity | null> {
  const clientId = sanitizeClientId(rawClientId);
  if (!clientId) return null;

  const session = await getAuthenticatedSession(request);
  if (session) {
    // Persist a configured owner grant (PREMIUM_ADMIN_EMAILS) so device
    // binding, /api/auth/me and this check all observe the same entitlement.
    // The grant requires an authenticated session with a matching email.
    let premium = false;
    try {
      premium = (await grantConfiguredPremium(session.userId, session.email))
        || (await isAdminPremiumEmail(session.email))
        || await getPremiumStatusByUserId(session.userId)
        || await getPremiumStatus(clientId);
    } catch {
      premium = false;
    }
    return {
      identity: `user:${session.userId}`,
      kind: "user",
      premium,
      email: session.email,
      userId: session.userId,
    };
  }

  return {
    identity: `client:${clientId}`,
    kind: "client",
    premium: await getPremiumStatus(clientId),
  };
}
