import type { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  const base = "https://allaboutpdfediting.xyz";

  return [
    { url: base, lastModified: new Date(), changeFrequency: "weekly", priority: 1 },
    { url: `${base}/compress`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/merge`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/split`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/image-to-pdf`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/pdf-to-images`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/extract-text`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/add-page-numbers`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/insert-blank`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/word-counter`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/annotate`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/pdf-to-excel`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/rotate`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/unlock`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/watermark`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/protect`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/html-to-pdf`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/sign`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/chat-pdf`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/batch`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/delete-pages`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/text-to-pdf`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/organize`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/metadata`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/resize`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/crop`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/fill-form`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/flatten-pdf`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/reverse-pdf`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/premium`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/about`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.4 },
    { url: `${base}/privacy`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.3 },
    { url: `${base}/terms`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.3 },
    { url: `${base}/blog`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.7 },
    { url: `${base}/blog/compress-pdf-without-losing-quality`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/blog/crop-pdf-margins`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/blog/delete-pages-from-pdf`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/blog/edit-pdf-metadata`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/blog/merge-multiple-pdfs-into-one`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/blog/organize-pdf-pages`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/blog/resize-pdf-pages`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/blog/text-to-pdf-converter`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/blog/sign-pdf-without-printing`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/blog/remove-password-from-pdf`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/blog/pdf-vs-image`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/blog/fill-pdf-forms-online`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/blog/flatten-pdf-online`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/blog/reverse-pdf-pages`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/blog/chat-with-pdf-ai`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/best-free-pdf-editor`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/smallpdf-alternative`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
  ];
}
