const navItems = [
  { name: "Compress PDF", url: "/compress" },
  { name: "Merge PDF", url: "/merge" },
  { name: "Split PDF", url: "/split" },
  { name: "Image to PDF", url: "/image-to-pdf" },
  { name: "PDF to Images", url: "/pdf-to-images" },
  { name: "Extract Text", url: "/extract-text" },
  { name: "Rotate PDF", url: "/rotate" },
  { name: "Protect PDF", url: "/protect" },
  { name: "Unlock PDF", url: "/unlock" },
  { name: "Sign PDF", url: "/sign" },
  { name: "Watermark PDF", url: "/watermark" },
  { name: "Resize PDF", url: "/resize" },
  { name: "Crop PDF", url: "/crop" },
  { name: "Organize Pages", url: "/organize" },
  { name: "Delete Pages", url: "/delete-pages" },
  { name: "Add Page Numbers", url: "/add-page-numbers" },
  { name: "Annotate PDF", url: "/annotate" },
  { name: "Redact PDF", url: "/redact" },
  { name: "Fill PDF Form", url: "/fill-form" },
  { name: "Flatten PDF", url: "/flatten-pdf" },
  { name: "PDF to Excel", url: "/pdf-to-excel" },
  { name: "Chat with PDF", url: "/chat-pdf" },
  { name: "HTML to PDF", url: "/html-to-pdf" },
  { name: "Text to PDF", url: "/text-to-pdf" },
  { name: "Word Counter", url: "/word-counter" },
  { name: "Insert Blank Pages", url: "/insert-blank" },
  { name: "Reverse PDF Order", url: "/reverse-pdf" },
  { name: "Metadata Editor", url: "/metadata" },
  { name: "Batch Process", url: "/batch" },
  { name: "PDF Diff", url: "/pdf-diff" },
  { name: "Certificate Generator", url: "/certificate-generator" },
  { name: "PDF to Audio", url: "/pdf-to-audio" },
  { name: "Form Data Extract", url: "/form-data-extract" },
  { name: "Bulk Rename", url: "/bulk-rename" },
  { name: "Booklet Creator", url: "/booklet" },
  { name: "Search & Redact", url: "/search-redact" },
  { name: "Color Inverter", url: "/pdf-inverter" },
  { name: "PDF Vault", url: "/vault" },
  { name: "QR Code Stamp", url: "/qr-stamp" },
  { name: "Metadata Sanitizer", url: "/metadata-sanitizer" },
  { name: "Split by Bookmarks", url: "/split-by-bookmarks" },
  { name: "Bates Numbering", url: "/bates-numbering" },
  { name: "Premium", url: "/premium" },
  { name: "Tools", url: "/tools" },
  { name: "Blog", url: "/blog" },
  { name: "About", url: "/about" },
  { name: "Contact", url: "/contact" },
  { name: "Privacy", url: "/privacy" },
  { name: "Terms", url: "/terms" },
  { name: "QA", url: "/qa" },
];

export default function SiteNavJsonLd() {
  const base = "https://allaboutpdfediting.xyz";
  const json = {
    "@context": "https://schema.org",
    "@type": "SiteNavigationElement",
    name: "Main Navigation",
    hasPart: navItems.map(({ name, url }) => ({
      "@type": "SiteNavigationElement",
      name,
      url: `${base}${url}`,
    })),
  };

  return <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(json) }} />;
}
